const fs = require('fs');
const path = require('path');

// All help translations for all languages
const translations = {
  es: {
    "help.general.intro.title": "Introducción a la aplicación",
    "help.general.intro.description": "La aplicación 3D Printer Calculator es una aplicación de escritorio para calcular costos de impresión 3D, gestionar cotizaciones y rastrear proyectos.",
    "help.general.intro.details": "La aplicación ayuda a calcular los costos de filamento, consumo de electricidad, costos de secado y costos de desgaste. Te permite crear, gestionar y exportar cotizaciones como PDF.",
    "help.general.navigation.title": "Navegación en la aplicación",
    "help.general.navigation.description": "Usa el menú izquierdo para navegar entre las diferentes partes de la aplicación.",
    "help.general.navigation.details": "El menú principal incluye: Inicio, Calculadora, Ofertas, Proyectos, Tareas, Filamentos, Impresoras, Clientes, Presupuesto y Configuración.",
    "help.calculations.basics.title": "Fundamentos del cálculo de costos",
    "help.calculations.basics.description": "La calculadora ayuda a calcular los costos de impresión 3D.",
    "help.calculations.basics.details": "Selecciona la impresora, los filamentos, ingresa la cantidad (gramos), el tiempo de impresión y el tiempo de secado. La aplicación calcula automáticamente los costos.",
    "help.calculations.costs.title": "Tipos de costos",
    "help.calculations.costs.description": "La aplicación calcula varios tipos de costos.",
    "help.calculations.costs.details": "Costo de filamento: basado en la cantidad y el precio del filamento usado. Costo de electricidad: basado en el tiempo de impresión y la potencia de la impresora. Costo de secado: basado en el tiempo de secado. Costo de desgaste: calculado basado en el tiempo de impresión.",
    "help.projects.create.title": "Crear un proyecto",
    "help.projects.create.description": "Crea nuevos proyectos para rastrear tu trabajo.",
    "help.projects.create.details": "Haz clic en el botón 'Nuevo proyecto', ingresa el nombre del proyecto, descripción, estado, progreso, fecha límite y presupuesto.",
    "help.projects.status.title": "Estados del proyecto",
    "help.projects.status.description": "Los proyectos pueden tener diferentes estados.",
    "help.projects.status.details": "Planificación: el proyecto aún se está planificando. En progreso: el proyecto está activamente en progreso. Completado: el proyecto está completado. En espera: el proyecto está en espera.",
    "help.tasks.create.title": "Crear una tarea",
    "help.tasks.create.description": "Crea tareas para rastrear tu trabajo.",
    "help.tasks.create.details": "Haz clic en el botón 'Nueva tarea', ingresa el título de la tarea, descripción, prioridad, estado, fecha de vencimiento y vincúlala a un proyecto u oferta.",
    "help.tasks.priority.title": "Prioridades de tareas",
    "help.tasks.priority.description": "Las tareas pueden tener prioridades.",
    "help.tasks.priority.details": "Baja: la tarea no es urgente. Media: tarea con prioridad normal. Alta: tarea urgente. Crítica: requiere atención inmediata.",
    "help.offers.create.title": "Crear una oferta",
    "help.offers.create.description": "Guarda los cálculos como ofertas.",
    "help.offers.create.details": "En la calculadora, después de calcular los costos, haz clic en el botón 'Guardar como oferta'. Ingresa los detalles del cliente, descripción y otra información.",
    "help.offers.status.title": "Estados de ofertas",
    "help.offers.status.description": "Puedes cambiar los estados de ofertas (Borrador, Enviado, Aceptado, Rechazado, Completado).",
    "help.offers.status.details": "Borrador: aún se está editando. Enviado: enviado al cliente. Aceptado: el cliente lo aceptó. Rechazado: el cliente lo rechazó. Completado: el trabajo está completado.",
    "help.filaments.add.title": "Agregar filamento",
    "help.filaments.add.description": "Agrega nuevos filamentos a tu colección.",
    "help.filaments.add.details": "Haz clic en el botón 'Nuevo filamento', ingresa la marca, tipo, color, precio y otra información. También puedes usar la biblioteca de filamentos para buscar colores.",
    "help.filaments.library.title": "Biblioteca de filamentos",
    "help.filaments.library.description": "La biblioteca de filamentos contiene más de 12,000 colores de fábrica. Selecciona por marca y tipo.",
    "help.filaments.library.details": "Más de 12,000 colores de fábrica están disponibles en la biblioteca. Puedes buscar por marca, tipo y color. Selecciona el color de la biblioteca y los datos del filamento se llenarán automáticamente.",
    "help.printers.add.title": "Agregar una impresora",
    "help.printers.add.description": "Agrega nuevas impresoras a la aplicación.",
    "help.printers.add.details": "Haz clic en el botón 'Nueva impresora', ingresa el nombre de la impresora, tipo, potencia y otra información. Si tienes un sistema AMS, también ingresa el número de ranuras AMS.",
    "help.customers.add.title": "Agregar un cliente",
    "help.customers.add.description": "Agrega nuevos clientes a la base de datos.",
    "help.customers.add.details": "Haz clic en el botón 'Nuevo cliente', ingresa su nombre, información de contacto, información de la empresa y otros datos.",
    "help.settings.general.title": "Configuración general",
    "help.settings.general.description": "Establece idioma, tema, animaciones y otras configuraciones generales.",
    "help.settings.general.details": "Aquí puedes establecer el idioma, tema, animaciones, guardado automático, configuraciones de respaldo y otras opciones generales.",
    "help.settings.backup.title": "Respaldo y restauración",
    "help.settings.backup.description": "Crea respaldos de tus datos o restáuralos desde versiones anteriores.",
    "help.settings.backup.details": "La aplicación crea respaldos automáticos. También puedes crear respaldos manualmente y restaurar tus datos desde un estado anterior.",
    "help.keyboard.shortcuts.title": "Atajos de teclado",
    "help.keyboard.shortcuts.description": "Usa atajos de teclado para trabajar más rápido.",
    "help.keyboard.shortcuts.details": "F1: Abrir menú de Ayuda, Ctrl+Z / Cmd+Z: Deshacer, Ctrl+Shift+Z / Cmd+Shift+Z: Rehacer, Ctrl+S / Cmd+S: Guardar, Escape: Cancelar/Cerrar.",
    "help.tips.efficiency.title": "Aumentar la eficiencia",
    "help.tips.efficiency.description": "Consejos para trabajar de manera eficiente.",
    "help.tips.efficiency.details": "Usa proyectos y tareas para organizar tu trabajo. Crea preajustes de filamentos para filamentos usados frecuentemente. Usa plantillas de ofertas para crear cotizaciones más rápidamente.",
  },
  fr: {
    "help.general.intro.title": "Introduction à l'application",
    "help.general.intro.description": "L'application 3D Printer Calculator est une application de bureau pour calculer les coûts d'impression 3D, gérer les devis et suivre les projets.",
    "help.general.intro.details": "L'application aide à calculer les coûts de filament, la consommation d'électricité, les coûts de séchage et les coûts d'usure. Elle vous permet de créer, gérer et exporter des devis en PDF.",
    "help.general.navigation.title": "Navigation dans l'application",
    "help.general.navigation.description": "Utilisez le menu de gauche pour naviguer entre les différentes parties de l'application.",
    "help.general.navigation.details": "Le menu principal comprend : Accueil, Calculatrice, Offres, Projets, Tâches, Filaments, Imprimantes, Clients, Budget et Paramètres.",
    "help.calculations.basics.title": "Bases du calcul des coûts",
    "help.calculations.basics.description": "La calculatrice aide à calculer les coûts d'impression 3D.",
    "help.calculations.basics.details": "Sélectionnez l'imprimante, les filaments, entrez la quantité (grammes), le temps d'impression et le temps de séchage. L'application calcule automatiquement les coûts.",
    "help.calculations.costs.title": "Types de coûts",
    "help.calculations.costs.description": "L'application calcule plusieurs types de coûts.",
    "help.calculations.costs.details": "Coût de filament : basé sur la quantité et le prix du filament utilisé. Coût d'électricité : basé sur le temps d'impression et la puissance de l'imprimante. Coût de séchage : basé sur le temps de séchage. Coût d'usure : calculé basé sur le temps d'impression.",
    "help.projects.create.title": "Créer un projet",
    "help.projects.create.description": "Créez de nouveaux projets pour suivre votre travail.",
    "help.projects.create.details": "Cliquez sur le bouton 'Nouveau projet', entrez le nom du projet, la description, le statut, la progression, la date limite et le budget.",
    "help.projects.status.title": "Statuts du projet",
    "help.projects.status.description": "Les projets peuvent avoir différents statuts.",
    "help.projects.status.details": "Planification : le projet est encore en cours de planification. En cours : le projet est activement en cours. Terminé : le projet est terminé. En attente : le projet est en attente.",
    "help.tasks.create.title": "Créer une tâche",
    "help.tasks.create.description": "Créez des tâches pour suivre votre travail.",
    "help.tasks.create.details": "Cliquez sur le bouton 'Nouvelle tâche', entrez le titre de la tâche, la description, la priorité, le statut, la date d'échéance et liez-la à un projet ou une offre.",
    "help.tasks.priority.title": "Priorités des tâches",
    "help.tasks.priority.description": "Les tâches peuvent avoir des priorités.",
    "help.tasks.priority.details": "Faible : la tâche n'est pas urgente. Moyenne : tâche avec priorité normale. Élevée : tâche urgente. Critique : nécessite une attention immédiate.",
    "help.offers.create.title": "Créer une offre",
    "help.offers.create.description": "Enregistrez les calculs comme offres.",
    "help.offers.create.details": "Dans la calculatrice, après avoir calculé les coûts, cliquez sur le bouton 'Enregistrer comme offre'. Entrez les détails du client, la description et d'autres informations.",
    "help.offers.status.title": "Statuts des offres",
    "help.offers.status.description": "Vous pouvez changer les statuts des offres (Brouillon, Envoyé, Accepté, Rejeté, Terminé).",
    "help.offers.status.details": "Brouillon : encore en cours d'édition. Envoyé : envoyé au client. Accepté : le client l'a accepté. Rejeté : le client l'a rejeté. Terminé : le travail est terminé.",
    "help.filaments.add.title": "Ajouter un filament",
    "help.filaments.add.description": "Ajoutez de nouveaux filaments à votre collection.",
    "help.filaments.add.details": "Cliquez sur le bouton 'Nouveau filament', entrez la marque, le type, la couleur, le prix et d'autres informations. Vous pouvez également utiliser la bibliothèque de filaments pour rechercher des couleurs.",
    "help.filaments.library.title": "Bibliothèque de filaments",
    "help.filaments.library.description": "La bibliothèque de filaments contient plus de 12 000 couleurs d'usine. Sélectionnez par marque et type.",
    "help.filaments.library.details": "Plus de 12 000 couleurs d'usine sont disponibles dans la bibliothèque. Vous pouvez rechercher par marque, type et couleur. Sélectionnez la couleur dans la bibliothèque et les données du filament seront automatiquement remplies.",
    "help.printers.add.title": "Ajouter une imprimante",
    "help.printers.add.description": "Ajoutez de nouvelles imprimantes à l'application.",
    "help.printers.add.details": "Cliquez sur le bouton 'Nouvelle imprimante', entrez le nom de l'imprimante, le type, la puissance et d'autres informations. Si vous avez un système AMS, entrez également le nombre d'emplacements AMS.",
    "help.customers.add.title": "Ajouter un client",
    "help.customers.add.description": "Ajoutez de nouveaux clients à la base de données.",
    "help.customers.add.details": "Cliquez sur le bouton 'Nouveau client', entrez son nom, ses informations de contact, les informations de l'entreprise et d'autres données.",
    "help.settings.general.title": "Paramètres généraux",
    "help.settings.general.description": "Définissez la langue, le thème, les animations et d'autres paramètres généraux.",
    "help.settings.general.details": "Ici vous pouvez définir la langue, le thème, les animations, la sauvegarde automatique, les paramètres de sauvegarde et d'autres options générales.",
    "help.settings.backup.title": "Sauvegarde et restauration",
    "help.settings.backup.description": "Créez des sauvegardes de vos données ou restaurez-les depuis des versions antérieures.",
    "help.settings.backup.details": "L'application crée des sauvegardes automatiques. Vous pouvez également créer manuellement des sauvegardes et restaurer vos données depuis un état antérieur.",
    "help.keyboard.shortcuts.title": "Raccourcis clavier",
    "help.keyboard.shortcuts.description": "Utilisez les raccourcis clavier pour travailler plus rapidement.",
    "help.keyboard.shortcuts.details": "F1 : Ouvrir le menu d'aide, Ctrl+Z / Cmd+Z : Annuler, Ctrl+Shift+Z / Cmd+Shift+Z : Rétablir, Ctrl+S / Cmd+S : Enregistrer, Escape : Annuler/Fermer.",
    "help.tips.efficiency.title": "Augmenter l'efficacité",
    "help.tips.efficiency.description": "Conseils pour travailler efficacement.",
    "help.tips.efficiency.details": "Utilisez des projets et des tâches pour organiser votre travail. Créez des préréglages de filaments pour les filaments fréquemment utilisés. Utilisez des modèles d'offres pour créer des devis plus rapidement.",
  },
  it: {
    "help.general.intro.title": "Introduzione all'applicazione",
    "help.general.intro.description": "L'applicazione 3D Printer Calculator è un'applicazione desktop per calcolare i costi di stampa 3D, gestire preventivi e monitorare progetti.",
    "help.general.intro.details": "L'applicazione aiuta a calcolare i costi del filamento, il consumo di elettricità, i costi di essiccazione e i costi di usura. Ti permette di creare, gestire ed esportare preventivi come PDF.",
    "help.general.navigation.title": "Navigazione nell'applicazione",
    "help.general.navigation.description": "Usa il menu sinistro per navigare tra le diverse parti dell'applicazione.",
    "help.general.navigation.details": "Il menu principale include: Home, Calcolatrice, Offerte, Progetti, Attività, Filamenti, Stampanti, Clienti, Bilancio e Impostazioni.",
    "help.calculations.basics.title": "Basi del calcolo dei costi",
    "help.calculations.basics.description": "La calcolatrice aiuta a calcolare i costi di stampa 3D.",
    "help.calculations.basics.details": "Seleziona la stampante, i filamenti, inserisci la quantità (grammi), il tempo di stampa e il tempo di essiccazione. L'applicazione calcola automaticamente i costi.",
    "help.calculations.costs.title": "Tipi di costi",
    "help.calculations.costs.description": "L'applicazione calcola diversi tipi di costi.",
    "help.calculations.costs.details": "Costo del filamento: basato sulla quantità e il prezzo del filamento usato. Costo dell'elettricità: basato sul tempo di stampa e la potenza della stampante. Costo di essiccazione: basato sul tempo di essiccazione. Costo di usura: calcolato basato sul tempo di stampa.",
    "help.projects.create.title": "Creare un progetto",
    "help.projects.create.description": "Crea nuovi progetti per monitorare il tuo lavoro.",
    "help.projects.create.details": "Clicca sul pulsante 'Nuovo progetto', inserisci il nome del progetto, descrizione, stato, progresso, scadenza e budget.",
    "help.projects.status.title": "Stati del progetto",
    "help.projects.status.description": "I progetti possono avere diversi stati.",
    "help.projects.status.details": "Pianificazione: il progetto è ancora in pianificazione. In corso: il progetto è attivamente in corso. Completato: il progetto è completato. In attesa: il progetto è in attesa.",
    "help.tasks.create.title": "Creare un'attività",
    "help.tasks.create.description": "Crea attività per monitorare il tuo lavoro.",
    "help.tasks.create.details": "Clicca sul pulsante 'Nuova attività', inserisci il titolo dell'attività, descrizione, priorità, stato, data di scadenza e collegala a un progetto o un'offerta.",
    "help.tasks.priority.title": "Priorità delle attività",
    "help.tasks.priority.description": "Le attività possono avere priorità.",
    "help.tasks.priority.details": "Bassa: l'attività non è urgente. Media: attività con priorità normale. Alta: attività urgente. Critica: richiede attenzione immediata.",
    "help.offers.create.title": "Creare un'offerta",
    "help.offers.create.description": "Salva i calcoli come offerte.",
    "help.offers.create.details": "Nella calcolatrice, dopo aver calcolato i costi, clicca sul pulsante 'Salva come offerta'. Inserisci i dettagli del cliente, descrizione e altre informazioni.",
    "help.offers.status.title": "Stati delle offerte",
    "help.offers.status.description": "Puoi cambiare gli stati delle offerte (Bozza, Inviata, Accettata, Rifiutata, Completata).",
    "help.offers.status.details": "Bozza: ancora in fase di modifica. Inviata: inviata al cliente. Accettata: il cliente l'ha accettata. Rifiutata: il cliente l'ha rifiutata. Completata: il lavoro è completato.",
    "help.filaments.add.title": "Aggiungere filamento",
    "help.filaments.add.description": "Aggiungi nuovi filamenti alla tua collezione.",
    "help.filaments.add.details": "Clicca sul pulsante 'Nuovo filamento', inserisci il marchio, tipo, colore, prezzo e altre informazioni. Puoi anche usare la libreria di filamenti per cercare colori.",
    "help.filaments.library.title": "Libreria di filamenti",
    "help.filaments.library.description": "La libreria di filamenti contiene oltre 12.000 colori di fabbrica. Seleziona per marchio e tipo.",
    "help.filaments.library.details": "Oltre 12.000 colori di fabbrica sono disponibili nella libreria. Puoi cercare per marchio, tipo e colore. Seleziona il colore dalla libreria e i dati del filamento verranno compilati automaticamente.",
    "help.printers.add.title": "Aggiungere una stampante",
    "help.printers.add.description": "Aggiungi nuove stampanti all'applicazione.",
    "help.printers.add.details": "Clicca sul pulsante 'Nuova stampante', inserisci il nome della stampante, tipo, potenza e altre informazioni. Se hai un sistema AMS, inserisci anche il numero di slot AMS.",
    "help.customers.add.title": "Aggiungere un cliente",
    "help.customers.add.description": "Aggiungi nuovi clienti al database.",
    "help.customers.add.details": "Clicca sul pulsante 'Nuovo cliente', inserisci il suo nome, informazioni di contatto, informazioni aziendali e altri dati.",
    "help.settings.general.title": "Impostazioni generali",
    "help.settings.general.description": "Imposta lingua, tema, animazioni e altre impostazioni generali.",
    "help.settings.general.details": "Qui puoi impostare la lingua, il tema, le animazioni, il salvataggio automatico, le impostazioni di backup e altre opzioni generali.",
    "help.settings.backup.title": "Backup e ripristino",
    "help.settings.backup.description": "Crea backup dei tuoi dati o ripristinali da versioni precedenti.",
    "help.settings.backup.details": "L'applicazione crea backup automatici. Puoi anche creare manualmente backup e ripristinare i tuoi dati da uno stato precedente.",
    "help.keyboard.shortcuts.title": "Scorciatoie da tastiera",
    "help.keyboard.shortcuts.description": "Usa le scorciatoie da tastiera per lavorare più velocemente.",
    "help.keyboard.shortcuts.details": "F1: Apri menu Aiuto, Ctrl+Z / Cmd+Z: Annulla, Ctrl+Shift+Z / Cmd+Shift+Z: Ripristina, Ctrl+S / Cmd+S: Salva, Escape: Annulla/Chiudi.",
    "help.tips.efficiency.title": "Aumentare l'efficienza",
    "help.tips.efficiency.description": "Consigli per lavorare in modo efficiente.",
    "help.tips.efficiency.details": "Usa progetti e attività per organizzare il tuo lavoro. Crea preset di filamenti per filamenti usati frequentemente. Usa modelli di offerte per creare preventivi più rapidamente.",
  },
  pl: {
    "help.general.intro.title": "Wprowadzenie do aplikacji",
    "help.general.intro.description": "Aplikacja 3D Printer Calculator to aplikacja desktopowa do obliczania kosztów druku 3D, zarządzania ofertami i śledzenia projektów.",
    "help.general.intro.details": "Aplikacja pomaga obliczyć koszty filamentu, zużycie energii elektrycznej, koszty suszenia i koszty zużycia. Pozwala tworzyć, zarządzać i eksportować oferty jako PDF.",
    "help.general.navigation.title": "Nawigacja w aplikacji",
    "help.general.navigation.description": "Użyj lewego menu do nawigacji między różnymi częściami aplikacji.",
    "help.general.navigation.details": "Menu główne zawiera: Strona główna, Kalkulator, Oferty, Projekty, Zadania, Filamenty, Drukarki, Klienci, Budżet i Ustawienia.",
    "help.calculations.basics.title": "Podstawy obliczania kosztów",
    "help.calculations.basics.description": "Kalkulator pomaga obliczyć koszty druku 3D.",
    "help.calculations.basics.details": "Wybierz drukarkę, filamenty, wprowadź ilość (gramy), czas druku i czas suszenia. Aplikacja automatycznie oblicza koszty.",
    "help.calculations.costs.title": "Typy kosztów",
    "help.calculations.costs.description": "Aplikacja oblicza kilka typów kosztów.",
    "help.calculations.costs.details": "Koszt filamentu: na podstawie ilości i ceny użytego filamentu. Koszt energii elektrycznej: na podstawie czasu druku i mocy drukarki. Koszt suszenia: na podstawie czasu suszenia. Koszt zużycia: obliczony na podstawie czasu druku.",
    "help.projects.create.title": "Tworzenie projektu",
    "help.projects.create.description": "Twórz nowe projekty, aby śledzić swoją pracę.",
    "help.projects.create.details": "Kliknij przycisk 'Nowy projekt', wprowadź nazwę projektu, opis, status, postęp, termin i budżet.",
    "help.projects.status.title": "Statusy projektu",
    "help.projects.status.description": "Projekty mogą mieć różne statusy.",
    "help.projects.status.details": "Planowanie: projekt jest nadal planowany. W toku: projekt jest aktywnie w toku. Ukończony: projekt jest ukończony. Wstrzymany: projekt jest wstrzymany.",
    "help.tasks.create.title": "Tworzenie zadania",
    "help.tasks.create.description": "Twórz zadania, aby śledzić swoją pracę.",
    "help.tasks.create.details": "Kliknij przycisk 'Nowe zadanie', wprowadź tytuł zadania, opis, priorytet, status, termin i powiąż je z projektem lub ofertą.",
    "help.tasks.priority.title": "Priorytety zadań",
    "help.tasks.priority.description": "Zadania mogą mieć priorytety.",
    "help.tasks.priority.details": "Niski: zadanie nie jest pilne. Średni: zadanie z normalnym priorytetem. Wysoki: pilne zadanie. Krytyczny: wymaga natychmiastowej uwagi.",
    "help.offers.create.title": "Tworzenie oferty",
    "help.offers.create.description": "Zapisz obliczenia jako oferty.",
    "help.offers.create.details": "W kalkulatorze po obliczeniu kosztów kliknij przycisk 'Zapisz jako ofertę'. Wprowadź dane klienta, opis i inne informacje.",
    "help.offers.status.title": "Statusy ofert",
    "help.offers.status.description": "Możesz zmieniać statusy ofert (Szkic, Wysłany, Zaakceptowany, Odrzucony, Ukończony).",
    "help.offers.status.details": "Szkic: nadal jest edytowany. Wysłany: wysłany do klienta. Zaakceptowany: klient go zaakceptował. Odrzucony: klient go odrzucił. Ukończony: praca jest ukończona.",
    "help.filaments.add.title": "Dodawanie filamentu",
    "help.filaments.add.description": "Dodaj nowe filamenty do swojej kolekcji.",
    "help.filaments.add.details": "Kliknij przycisk 'Nowy filament', wprowadź markę, typ, kolor, cenę i inne informacje. Możesz również użyć biblioteki filamentów do wyszukiwania kolorów.",
    "help.filaments.library.title": "Biblioteka filamentów",
    "help.filaments.library.description": "Biblioteka filamentów zawiera ponad 12 000 kolorów fabrycznych. Wybierz według marki i typu.",
    "help.filaments.library.details": "W bibliotece dostępnych jest ponad 12 000 kolorów fabrycznych. Możesz wyszukiwać według marki, typu i koloru. Wybierz kolor z biblioteki, a dane filamentu zostaną automatycznie wypełnione.",
    "help.printers.add.title": "Dodawanie drukarki",
    "help.printers.add.description": "Dodaj nowe drukarki do aplikacji.",
    "help.printers.add.details": "Kliknij przycisk 'Nowa drukarka', wprowadź nazwę drukarki, typ, moc i inne informacje. Jeśli masz system AMS, wprowadź również liczbę slotów AMS.",
    "help.customers.add.title": "Dodawanie klienta",
    "help.customers.add.description": "Dodaj nowych klientów do bazy danych.",
    "help.customers.add.details": "Kliknij przycisk 'Nowy klient', wprowadź jego imię, dane kontaktowe, informacje o firmie i inne dane.",
    "help.settings.general.title": "Ustawienia ogólne",
    "help.settings.general.description": "Ustaw język, motyw, animacje i inne ustawienia ogólne.",
    "help.settings.general.details": "Tutaj możesz ustawić język, motyw, animacje, automatyczne zapisywanie, ustawienia kopii zapasowych i inne opcje ogólne.",
    "help.settings.backup.title": "Kopia zapasowa i przywracanie",
    "help.settings.backup.description": "Twórz kopie zapasowe swoich danych lub przywracaj je z poprzednich wersji.",
    "help.settings.backup.details": "Aplikacja tworzy automatyczne kopie zapasowe. Możesz również ręcznie tworzyć kopie zapasowe i przywracać swoje dane z poprzedniego stanu.",
    "help.keyboard.shortcuts.title": "Skróty klawiszowe",
    "help.keyboard.shortcuts.description": "Używaj skrótów klawiszowych do szybszej pracy.",
    "help.keyboard.shortcuts.details": "F1: Otwórz menu Pomocy, Ctrl+Z / Cmd+Z: Cofnij, Ctrl+Shift+Z / Cmd+Shift+Z: Przywróć, Ctrl+S / Cmd+S: Zapisz, Escape: Anuluj/Zamknij.",
    "help.tips.efficiency.title": "Zwiększanie wydajności",
    "help.tips.efficiency.description": "Wskazówki dotyczące efektywnej pracy.",
    "help.tips.efficiency.details": "Używaj projektów i zadań do organizowania swojej pracy. Twórz ustawienia wstępne filamentów dla często używanych filamentów. Używaj szablonów ofert do szybszego tworzenia ofert.",
  },
  pt: {
    "help.general.intro.title": "Introdução ao aplicativo",
    "help.general.intro.description": "O aplicativo 3D Printer Calculator é um aplicativo de desktop para calcular custos de impressão 3D, gerenciar cotações e acompanhar projetos.",
    "help.general.intro.details": "O aplicativo ajuda a calcular os custos do filamento, consumo de eletricidade, custos de secagem e custos de desgaste. Permite criar, gerenciar e exportar cotações como PDF.",
    "help.general.navigation.title": "Navegação no aplicativo",
    "help.general.navigation.description": "Use o menu esquerdo para navegar entre as diferentes partes do aplicativo.",
    "help.general.navigation.details": "O menu principal inclui: Início, Calculadora, Ofertas, Projetos, Tarefas, Filamentos, Impressoras, Clientes, Orçamento e Configurações.",
    "help.calculations.basics.title": "Fundamentos do cálculo de custos",
    "help.calculations.basics.description": "A calculadora ajuda a calcular os custos de impressão 3D.",
    "help.calculations.basics.details": "Selecione a impressora, os filamentos, insira a quantidade (gramas), o tempo de impressão e o tempo de secagem. O aplicativo calcula automaticamente os custos.",
    "help.calculations.costs.title": "Tipos de custos",
    "help.calculations.costs.description": "O aplicativo calcula vários tipos de custos.",
    "help.calculations.costs.details": "Custo do filamento: baseado na quantidade e preço do filamento usado. Custo de eletricidade: baseado no tempo de impressão e potência da impressora. Custo de secagem: baseado no tempo de secagem. Custo de desgaste: calculado baseado no tempo de impressão.",
    "help.projects.create.title": "Criar um projeto",
    "help.projects.create.description": "Crie novos projetos para acompanhar seu trabalho.",
    "help.projects.create.details": "Clique no botão 'Novo projeto', insira o nome do projeto, descrição, status, progresso, prazo e orçamento.",
    "help.projects.status.title": "Status do projeto",
    "help.projects.status.description": "Os projetos podem ter diferentes status.",
    "help.projects.status.details": "Planejamento: o projeto ainda está sendo planejado. Em andamento: o projeto está ativamente em andamento. Concluído: o projeto está concluído. Em espera: o projeto está em espera.",
    "help.tasks.create.title": "Criar uma tarefa",
    "help.tasks.create.description": "Crie tarefas para acompanhar seu trabalho.",
    "help.tasks.create.details": "Clique no botão 'Nova tarefa', insira o título da tarefa, descrição, prioridade, status, data de vencimento e vincule-a a um projeto ou oferta.",
    "help.tasks.priority.title": "Prioridades de tarefas",
    "help.tasks.priority.description": "As tarefas podem ter prioridades.",
    "help.tasks.priority.details": "Baixa: a tarefa não é urgente. Média: tarefa com prioridade normal. Alta: tarefa urgente. Crítica: requer atenção imediata.",
    "help.offers.create.title": "Criar uma oferta",
    "help.offers.create.description": "Salve os cálculos como ofertas.",
    "help.offers.create.details": "Na calculadora, após calcular os custos, clique no botão 'Salvar como oferta'. Insira os detalhes do cliente, descrição e outras informações.",
    "help.offers.status.title": "Status das ofertas",
    "help.offers.status.description": "Você pode alterar os status das ofertas (Rascunho, Enviado, Aceito, Rejeitado, Concluído).",
    "help.offers.status.details": "Rascunho: ainda está sendo editado. Enviado: enviado ao cliente. Aceito: o cliente aceitou. Rejeitado: o cliente rejeitou. Concluído: o trabalho está concluído.",
    "help.filaments.add.title": "Adicionar filamento",
    "help.filaments.add.description": "Adicione novos filamentos à sua coleção.",
    "help.filaments.add.details": "Clique no botão 'Novo filamento', insira a marca, tipo, cor, preço e outras informações. Você também pode usar a biblioteca de filamentos para pesquisar cores.",
    "help.filaments.library.title": "Biblioteca de filamentos",
    "help.filaments.library.description": "A biblioteca de filamentos contém mais de 12.000 cores de fábrica. Selecione por marca e tipo.",
    "help.filaments.library.details": "Mais de 12.000 cores de fábrica estão disponíveis na biblioteca. Você pode pesquisar por marca, tipo e cor. Selecione a cor da biblioteca e os dados do filamento serão preenchidos automaticamente.",
    "help.printers.add.title": "Adicionar uma impressora",
    "help.printers.add.description": "Adicione novas impressoras ao aplicativo.",
    "help.printers.add.details": "Clique no botão 'Nova impressora', insira o nome da impressora, tipo, potência e outras informações. Se você tiver um sistema AMS, insira também o número de slots AMS.",
    "help.customers.add.title": "Adicionar um cliente",
    "help.customers.add.description": "Adicione novos clientes ao banco de dados.",
    "help.customers.add.details": "Clique no botão 'Novo cliente', insira seu nome, informações de contato, informações da empresa e outros dados.",
    "help.settings.general.title": "Configurações gerais",
    "help.settings.general.description": "Defina idioma, tema, animações e outras configurações gerais.",
    "help.settings.general.details": "Aqui você pode definir o idioma, tema, animações, salvamento automático, configurações de backup e outras opções gerais.",
    "help.settings.backup.title": "Backup e restauração",
    "help.settings.backup.description": "Crie backups dos seus dados ou restaure-os de versões anteriores.",
    "help.settings.backup.details": "O aplicativo cria backups automáticos. Você também pode criar backups manualmente e restaurar seus dados de um estado anterior.",
    "help.keyboard.shortcuts.title": "Atalhos de teclado",
    "help.keyboard.shortcuts.description": "Use atalhos de teclado para trabalhar mais rápido.",
    "help.keyboard.shortcuts.details": "F1: Abrir menu de Ajuda, Ctrl+Z / Cmd+Z: Desfazer, Ctrl+Shift+Z / Cmd+Shift+Z: Refazer, Ctrl+S / Cmd+S: Salvar, Escape: Cancelar/Fechar.",
    "help.tips.efficiency.title": "Aumentar a eficiência",
    "help.tips.efficiency.description": "Dicas para trabalhar de forma eficiente.",
    "help.tips.efficiency.details": "Use projetos e tarefas para organizar seu trabalho. Crie predefinições de filamentos para filamentos usados frequentemente. Use modelos de ofertas para criar cotações mais rapidamente.",
  },
  ru: {
    "help.general.intro.title": "Введение в приложение",
    "help.general.intro.description": "Приложение 3D Printer Calculator - это настольное приложение для расчета стоимости 3D-печати, управления предложениями и отслеживания проектов.",
    "help.general.intro.details": "Приложение помогает рассчитать стоимость филамента, потребление электроэнергии, стоимость сушки и износа. Позволяет создавать, управлять и экспортировать предложения в формате PDF.",
    "help.general.navigation.title": "Навигация в приложении",
    "help.general.navigation.description": "Используйте левое меню для навигации между различными частями приложения.",
    "help.general.navigation.details": "Главное меню включает: Главная, Калькулятор, Предложения, Проекты, Задачи, Филаменты, Принтеры, Клиенты, Бюджет и Настройки.",
    "help.calculations.basics.title": "Основы расчета стоимости",
    "help.calculations.basics.description": "Калькулятор помогает рассчитать стоимость 3D-печати.",
    "help.calculations.basics.details": "Выберите принтер, филаменты, введите количество (граммы), время печати и время сушки. Приложение автоматически рассчитывает стоимость.",
    "help.calculations.costs.title": "Типы затрат",
    "help.calculations.costs.description": "Приложение рассчитывает несколько типов затрат.",
    "help.calculations.costs.details": "Стоимость филамента: на основе количества и цены используемого филамента. Стоимость электроэнергии: на основе времени печати и мощности принтера. Стоимость сушки: на основе времени сушки. Стоимость износа: рассчитывается на основе времени печати.",
    "help.projects.create.title": "Создание проекта",
    "help.projects.create.description": "Создавайте новые проекты для отслеживания вашей работы.",
    "help.projects.create.details": "Нажмите кнопку 'Новый проект', введите название проекта, описание, статус, прогресс, срок и бюджет.",
    "help.projects.status.title": "Статусы проекта",
    "help.projects.status.description": "Проекты могут иметь разные статусы.",
    "help.projects.status.details": "Планирование: проект все еще планируется. В процессе: проект активно выполняется. Завершен: проект завершен. Приостановлен: проект приостановлен.",
    "help.tasks.create.title": "Создание задачи",
    "help.tasks.create.description": "Создавайте задачи для отслеживания вашей работы.",
    "help.tasks.create.details": "Нажмите кнопку 'Новая задача', введите название задачи, описание, приоритет, статус, срок выполнения и свяжите ее с проектом или предложением.",
    "help.tasks.priority.title": "Приоритеты задач",
    "help.tasks.priority.description": "Задачи могут иметь приоритеты.",
    "help.tasks.priority.details": "Низкий: задача не срочная. Средний: задача с обычным приоритетом. Высокий: срочная задача. Критический: требует немедленного внимания.",
    "help.offers.create.title": "Создание предложения",
    "help.offers.create.description": "Сохраняйте расчеты как предложения.",
    "help.offers.create.details": "В калькуляторе после расчета стоимости нажмите кнопку 'Сохранить как предложение'. Введите данные клиента, описание и другую информацию.",
    "help.offers.status.title": "Статусы предложений",
    "help.offers.status.description": "Вы можете изменить статусы предложений (Черновик, Отправлено, Принято, Отклонено, Завершено).",
    "help.offers.status.details": "Черновик: еще редактируется. Отправлено: отправлено клиенту. Принято: клиент принял. Отклонено: клиент отклонил. Завершено: работа завершена.",
    "help.filaments.add.title": "Добавление филамента",
    "help.filaments.add.description": "Добавляйте новые филаменты в свою коллекцию.",
    "help.filaments.add.details": "Нажмите кнопку 'Новый филамент', введите марку, тип, цвет, цену и другую информацию. Вы также можете использовать библиотеку филаментов для поиска цветов.",
    "help.filaments.library.title": "Библиотека филаментов",
    "help.filaments.library.description": "Библиотека филаментов содержит более 12 000 заводских цветов. Выберите по марке и типу.",
    "help.filaments.library.details": "В библиотеке доступно более 12 000 заводских цветов. Вы можете искать по марке, типу и цвету. Выберите цвет из библиотеки, и данные филамента будут автоматически заполнены.",
    "help.printers.add.title": "Добавление принтера",
    "help.printers.add.description": "Добавляйте новые принтеры в приложение.",
    "help.printers.add.details": "Нажмите кнопку 'Новый принтер', введите название принтера, тип, мощность и другую информацию. Если у вас есть система AMS, также введите количество слотов AMS.",
    "help.customers.add.title": "Добавление клиента",
    "help.customers.add.description": "Добавляйте новых клиентов в базу данных.",
    "help.customers.add.details": "Нажмите кнопку 'Новый клиент', введите его имя, контактную информацию, информацию о компании и другие данные.",
    "help.settings.general.title": "Общие настройки",
    "help.settings.general.description": "Установите язык, тему, анимации и другие общие настройки.",
    "help.settings.general.details": "Здесь вы можете установить язык, тему, анимации, автоматическое сохранение, настройки резервного копирования и другие общие параметры.",
    "help.settings.backup.title": "Резервное копирование и восстановление",
    "help.settings.backup.description": "Создавайте резервные копии ваших данных или восстанавливайте их из предыдущих версий.",
    "help.settings.backup.details": "Приложение создает автоматические резервные копии. Вы также можете вручную создавать резервные копии и восстанавливать свои данные из предыдущего состояния.",
    "help.keyboard.shortcuts.title": "Горячие клавиши",
    "help.keyboard.shortcuts.description": "Используйте горячие клавиши для более быстрой работы.",
    "help.keyboard.shortcuts.details": "F1: Открыть меню справки, Ctrl+Z / Cmd+Z: Отменить, Ctrl+Shift+Z / Cmd+Shift+Z: Повторить, Ctrl+S / Cmd+S: Сохранить, Escape: Отмена/Закрыть.",
    "help.tips.efficiency.title": "Повышение эффективности",
    "help.tips.efficiency.description": "Советы по эффективной работе.",
    "help.tips.efficiency.details": "Используйте проекты и задачи для организации вашей работы. Создавайте предустановки филаментов для часто используемых филаментов. Используйте шаблоны предложений для более быстрого создания предложений.",
  },
  sk: {
    "help.general.intro.title": "Úvod do aplikácie",
    "help.general.intro.description": "Aplikácia 3D Printer Calculator je desktopová aplikácia na výpočet nákladov na 3D tlač, správu ponúk a sledovanie projektov.",
    "help.general.intro.details": "Aplikácia pomáha vypočítať náklady na filament, spotrebu elektriny, náklady na sušenie a opotrebovanie. Umožňuje vytvárať, spravovať a exportovať ponuky ako PDF.",
    "help.general.navigation.title": "Navigácia v aplikácii",
    "help.general.navigation.description": "Použite ľavé menu na navigáciu medzi rôznymi časťami aplikácie.",
    "help.general.navigation.details": "Hlavné menu obsahuje: Domov, Kalkulačka, Ponuky, Projekty, Úlohy, Filamenty, Tlačiarne, Zákazníci, Rozpočet a Nastavenia.",
    "help.calculations.basics.title": "Základy výpočtu nákladov",
    "help.calculations.basics.description": "Kalkulačka pomáha vypočítať náklady na 3D tlač.",
    "help.calculations.basics.details": "Vyberte tlačiareň, filamenty, zadajte množstvo (gramy), čas tlače a čas sušenia. Aplikácia automaticky vypočíta náklady.",
    "help.calculations.costs.title": "Typy nákladov",
    "help.calculations.costs.description": "Aplikácia počíta niekoľko typov nákladov.",
    "help.calculations.costs.details": "Náklady na filament: na základe množstva a ceny použitého filamentu. Náklady na elektrinu: na základe času tlače a výkonu tlačiarne. Náklady na sušenie: na základe času sušenia. Náklady na opotrebovanie: vypočítané na základe času tlače.",
    "help.projects.create.title": "Vytvorenie projektu",
    "help.projects.create.description": "Vytvárajte nové projekty na sledovanie vašej práce.",
    "help.projects.create.details": "Kliknite na tlačidlo 'Nový projekt', zadajte názov projektu, popis, stav, pokrok, termín a rozpočet.",
    "help.projects.status.title": "Stavy projektu",
    "help.projects.status.description": "Projekty môžu mať rôzne stavy.",
    "help.projects.status.details": "Plánovanie: projekt sa stále plánuje. V priebehu: projekt je aktívne v priebehu. Dokončené: projekt je dokončený. Pozastavené: projekt je pozastavený.",
    "help.tasks.create.title": "Vytvorenie úlohy",
    "help.tasks.create.description": "Vytvárajte úlohy na sledovanie vašej práce.",
    "help.tasks.create.details": "Kliknite na tlačidlo 'Nová úloha', zadajte názov úlohy, popis, prioritu, stav, termín a prepojte ju s projektom alebo ponukou.",
    "help.tasks.priority.title": "Priority úloh",
    "help.tasks.priority.description": "Úlohy môžu mať priority.",
    "help.tasks.priority.details": "Nízka: úloha nie je naliehavá. Stredná: úloha s normálnou prioritou. Vysoká: naliehavá úloha. Kritická: vyžaduje okamžitú pozornosť.",
    "help.offers.create.title": "Vytvorenie ponuky",
    "help.offers.create.description": "Uložte výpočty ako ponuky.",
    "help.offers.create.details": "V kalkulačke po výpočte nákladov kliknite na tlačidlo 'Uložiť ako ponuku'. Zadajte údaje o zákazníkovi, popis a ďalšie informácie.",
    "help.offers.status.title": "Stavy ponúk",
    "help.offers.status.description": "Môžete zmeniť stavy ponúk (Návrh, Odoslané, Prijaté, Zamietnuté, Dokončené).",
    "help.offers.status.details": "Návrh: stále sa upravuje. Odoslané: odoslané zákazníkovi. Prijaté: zákazník to prijal. Zamietnuté: zákazník to zamietol. Dokončené: práca je dokončená.",
    "help.filaments.add.title": "Pridanie filamentu",
    "help.filaments.add.description": "Pridajte nové filamenty do vašej zbierky.",
    "help.filaments.add.details": "Kliknite na tlačidlo 'Nový filament', zadajte značku, typ, farbu, cenu a ďalšie informácie. Môžete tiež použiť knižnicu filamentov na vyhľadávanie farieb.",
    "help.filaments.library.title": "Knižnica filamentov",
    "help.filaments.library.description": "Knižnica filamentov obsahuje viac ako 12 000 továrenských farieb. Vyberte podľa značky a typu.",
    "help.filaments.library.details": "V knižnici je k dispozícii viac ako 12 000 továrenských farieb. Môžete vyhľadávať podľa značky, typu a farby. Vyberte farbu z knižnice a údaje o filamente sa automaticky vyplnia.",
    "help.printers.add.title": "Pridanie tlačiarne",
    "help.printers.add.description": "Pridajte nové tlačiarne do aplikácie.",
    "help.printers.add.details": "Kliknite na tlačidlo 'Nová tlačiareň', zadajte názov tlačiarne, typ, výkon a ďalšie informácie. Ak máte systém AMS, zadajte tiež počet slotov AMS.",
    "help.customers.add.title": "Pridanie zákazníka",
    "help.customers.add.description": "Pridajte nových zákazníkov do databázy.",
    "help.customers.add.details": "Kliknite na tlačidlo 'Nový zákazník', zadajte jeho meno, kontaktné údaje, informácie o spoločnosti a ďalšie údaje.",
    "help.settings.general.title": "Všeobecné nastavenia",
    "help.settings.general.description": "Nastavte jazyk, tému, animácie a ďalšie všeobecné nastavenia.",
    "help.settings.general.details": "Tu môžete nastaviť jazyk, tému, animácie, automatické ukladanie, nastavenia zálohovania a ďalšie všeobecné možnosti.",
    "help.settings.backup.title": "Zálohovanie a obnovenie",
    "help.settings.backup.description": "Vytvárajte zálohy vašich dát alebo ich obnovte z predchádzajúcich verzii.",
    "help.settings.backup.details": "Aplikácia vytvára automatické zálohy. Môžete tiež ručne vytvárať zálohy a obnoviť vaše dáta z predchádzajúceho stavu.",
    "help.keyboard.shortcuts.title": "Klávesové skratky",
    "help.keyboard.shortcuts.description": "Používajte klávesové skratky na rýchlejšiu prácu.",
    "help.keyboard.shortcuts.details": "F1: Otvoriť ponuku Pomoc, Ctrl+Z / Cmd+Z: Späť, Ctrl+Shift+Z / Cmd+Shift+Z: Znova, Ctrl+S / Cmd+S: Uložiť, Escape: Zrušiť/Zatvoriť.",
    "help.tips.efficiency.title": "Zvyšovanie efektivity",
    "help.tips.efficiency.description": "Tipy na efektívnu prácu.",
    "help.tips.efficiency.details": "Používajte projekty a úlohy na organizáciu vašej práce. Vytvárajte predvolby filamentov pre často používané filamenty. Používajte šablóny ponúk na rýchlejšie vytváranie ponúk.",
  },
  uk: {
    "help.general.intro.title": "Вступ до програми",
    "help.general.intro.description": "Програма 3D Printer Calculator - це настільна програма для розрахунку вартості 3D-друку, управління пропозиціями та відстеження проектів.",
    "help.general.intro.details": "Програма допомагає розрахувати вартість філаменту, споживання електроенергії, вартість сушіння та зносу. Дозволяє створювати, керувати та експортувати пропозиції у форматі PDF.",
    "help.general.navigation.title": "Навігація в програмі",
    "help.general.navigation.description": "Використовуйте ліве меню для навігації між різними частинами програми.",
    "help.general.navigation.details": "Головне меню включає: Головна, Калькулятор, Пропозиції, Проєкти, Завдання, Філаменти, Принтери, Клієнти, Бюджет та Налаштування.",
    "help.calculations.basics.title": "Основи розрахунку вартості",
    "help.calculations.basics.description": "Калькулятор допомагає розрахувати вартість 3D-друку.",
    "help.calculations.basics.details": "Виберіть принтер, філаменти, введіть кількість (грами), час друку та час сушіння. Програма автоматично розраховує вартість.",
    "help.calculations.costs.title": "Типи витрат",
    "help.calculations.costs.description": "Програма розраховує кілька типів витрат.",
    "help.calculations.costs.details": "Вартість філаменту: на основі кількості та ціни використаного філаменту. Вартість електроенергії: на основі часу друку та потужності принтера. Вартість сушіння: на основі часу сушіння. Вартість зносу: розраховується на основі часу друку.",
    "help.projects.create.title": "Створення проєкту",
    "help.projects.create.description": "Створюйте нові проєкти для відстеження вашої роботи.",
    "help.projects.create.details": "Натисніть кнопку 'Новий проєкт', введіть назву проєкту, опис, статус, прогрес, термін та бюджет.",
    "help.projects.status.title": "Статуси проєкту",
    "help.projects.status.description": "Проєкти можуть мати різні статуси.",
    "help.projects.status.details": "Планування: проєкт ще планується. В процесі: проєкт активно виконується. Завершено: проєкт завершено. Призупинено: проєкт призупинено.",
    "help.tasks.create.title": "Створення завдання",
    "help.tasks.create.description": "Створюйте завдання для відстеження вашої роботи.",
    "help.tasks.create.details": "Натисніть кнопку 'Нове завдання', введіть назву завдання, опис, пріоритет, статус, термін виконання та зв'яжіть його з проєктом або пропозицією.",
    "help.tasks.priority.title": "Пріоритети завдань",
    "help.tasks.priority.description": "Завдання можуть мати пріоритети.",
    "help.tasks.priority.details": "Низький: завдання не термінове. Середній: завдання зі звичайним пріоритетом. Високий: термінове завдання. Критичний: потребує негайної уваги.",
    "help.offers.create.title": "Створення пропозиції",
    "help.offers.create.description": "Зберігайте розрахунки як пропозиції.",
    "help.offers.create.details": "У калькуляторі після розрахунку вартості натисніть кнопку 'Зберегти як пропозицію'. Введіть дані клієнта, опис та іншу інформацію.",
    "help.offers.status.title": "Статуси пропозицій",
    "help.offers.status.description": "Ви можете змінити статуси пропозицій (Чернетка, Відправлено, Прийнято, Відхилено, Завершено).",
    "help.offers.status.details": "Чернетка: ще редагується. Відправлено: відправлено клієнту. Прийнято: клієнт прийняв. Відхилено: клієнт відхилив. Завершено: робота завершена.",
    "help.filaments.add.title": "Додавання філаменту",
    "help.filaments.add.description": "Додавайте нові філаменти до вашої колекції.",
    "help.filaments.add.details": "Натисніть кнопку 'Новий філамент', введіть марку, тип, колір, ціну та іншу інформацію. Ви також можете використовувати бібліотеку філаментів для пошуку кольорів.",
    "help.filaments.library.title": "Бібліотека філаментів",
    "help.filaments.library.description": "Бібліотека філаментів містить понад 12 000 заводських кольорів. Виберіть за маркою та типом.",
    "help.filaments.library.details": "У бібліотеці доступно понад 12 000 заводських кольорів. Ви можете шукати за маркою, типом та кольором. Виберіть колір з бібліотеки, і дані філаменту будуть автоматично заповнені.",
    "help.printers.add.title": "Додавання принтера",
    "help.printers.add.description": "Додавайте нові принтери до програми.",
    "help.printers.add.details": "Натисніть кнопку 'Новий принтер', введіть назву принтера, тип, потужність та іншу інформацію. Якщо у вас є система AMS, також введіть кількість слотів AMS.",
    "help.customers.add.title": "Додавання клієнта",
    "help.customers.add.description": "Додавайте нових клієнтів до бази даних.",
    "help.customers.add.details": "Натисніть кнопку 'Новий клієнт', введіть його ім'я, контактну інформацію, інформацію про компанію та інші дані.",
    "help.settings.general.title": "Загальні налаштування",
    "help.settings.general.description": "Встановіть мову, тему, анімації та інші загальні налаштування.",
    "help.settings.general.details": "Тут ви можете встановити мову, тему, анімації, автоматичне збереження, налаштування резервного копіювання та інші загальні параметри.",
    "help.settings.backup.title": "Резервне копіювання та відновлення",
    "help.settings.backup.description": "Створюйте резервні копії ваших даних або відновлюйте їх з попередніх версій.",
    "help.settings.backup.details": "Програма створює автоматичні резервні копії. Ви також можете вручну створювати резервні копії та відновлювати свої дані з попереднього стану.",
    "help.keyboard.shortcuts.title": "Гарячі клавіші",
    "help.keyboard.shortcuts.description": "Використовуйте гарячі клавіші для швидшої роботи.",
    "help.keyboard.shortcuts.details": "F1: Відкрити меню довідки, Ctrl+Z / Cmd+Z: Скасувати, Ctrl+Shift+Z / Cmd+Shift+Z: Повторити, Ctrl+S / Cmd+S: Зберегти, Escape: Скасувати/Закрити.",
    "help.tips.efficiency.title": "Підвищення ефективності",
    "help.tips.efficiency.description": "Поради щодо ефективної роботи.",
    "help.tips.efficiency.details": "Використовуйте проєкти та завдання для організації вашої роботи. Створюйте пресети філаментів для часто використовуваних філаментів. Використовуйте шаблони пропозицій для швидшого створення пропозицій.",
  },
  zh: {
    "help.general.intro.title": "应用程序介绍",
    "help.general.intro.description": "3D打印机计算器应用程序是一个桌面应用程序，用于计算3D打印成本、管理报价和跟踪项目。",
    "help.general.intro.details": "该应用程序帮助计算耗材成本、电力消耗、干燥成本和磨损成本。它允许您创建、管理和将报价导出为PDF。",
    "help.general.navigation.title": "应用程序中的导航",
    "help.general.navigation.description": "使用左侧菜单在应用程序的不同部分之间导航。",
    "help.general.navigation.details": "主菜单包括：首页、计算器、报价、项目、任务、耗材、打印机、客户、预算和设置。",
    "help.calculations.basics.title": "成本计算基础",
    "help.calculations.basics.description": "计算器帮助计算3D打印成本。",
    "help.calculations.basics.details": "选择打印机、耗材，输入数量（克）、打印时间和干燥时间。应用程序自动计算成本。",
    "help.calculations.costs.title": "成本类型",
    "help.calculations.costs.description": "应用程序计算多种类型的成本。",
    "help.calculations.costs.details": "耗材成本：基于使用的耗材数量和价格。电力成本：基于打印时间和打印机功率。干燥成本：基于干燥时间。磨损成本：根据打印时间计算。",
    "help.projects.create.title": "创建项目",
    "help.projects.create.description": "创建新项目以跟踪您的工作。",
    "help.projects.create.details": "点击'新项目'按钮，输入项目名称、描述、状态、进度、截止日期和预算。",
    "help.projects.status.title": "项目状态",
    "help.projects.status.description": "项目可以有不同的状态。",
    "help.projects.status.details": "规划中：项目仍在规划中。进行中：项目正在积极进行中。已完成：项目已完成。暂停：项目已暂停。",
    "help.tasks.create.title": "创建任务",
    "help.tasks.create.description": "创建任务以跟踪您的工作。",
    "help.tasks.create.details": "点击'新任务'按钮，输入任务标题、描述、优先级、状态、截止日期，并将其链接到项目或报价。",
    "help.tasks.priority.title": "任务优先级",
    "help.tasks.priority.description": "任务可以有优先级。",
    "help.tasks.priority.details": "低：任务不紧急。中：正常优先级的任务。高：紧急任务。关键：需要立即关注。",
    "help.offers.create.title": "创建报价",
    "help.offers.create.description": "将计算保存为报价。",
    "help.offers.create.details": "在计算器中，计算成本后，点击'保存为报价'按钮。输入客户详细信息、描述和其他信息。",
    "help.offers.status.title": "报价状态",
    "help.offers.status.description": "您可以更改报价状态（草稿、已发送、已接受、已拒绝、已完成）。",
    "help.offers.status.details": "草稿：仍在编辑中。已发送：已发送给客户。已接受：客户已接受。已拒绝：客户已拒绝。已完成：工作已完成。",
    "help.filaments.add.title": "添加耗材",
    "help.filaments.add.description": "向您的集合添加新耗材。",
    "help.filaments.add.details": "点击'新耗材'按钮，输入品牌、类型、颜色、价格和其他信息。您也可以使用耗材库搜索颜色。",
    "help.filaments.library.title": "耗材库",
    "help.filaments.library.description": "耗材库包含超过12,000种工厂颜色。按品牌和类型选择。",
    "help.filaments.library.details": "库中有超过12,000种工厂颜色可用。您可以按品牌、类型和颜色搜索。从库中选择颜色，耗材数据将自动填充。",
    "help.printers.add.title": "添加打印机",
    "help.printers.add.description": "向应用程序添加新打印机。",
    "help.printers.add.details": "点击'新打印机'按钮，输入打印机名称、类型、功率和其他信息。如果您有AMS系统，也请输入AMS插槽数量。",
    "help.customers.add.title": "添加客户",
    "help.customers.add.description": "向数据库添加新客户。",
    "help.customers.add.details": "点击'新客户'按钮，输入他们的姓名、联系信息、公司信息和其他数据。",
    "help.settings.general.title": "常规设置",
    "help.settings.general.description": "设置语言、主题、动画和其他常规设置。",
    "help.settings.general.details": "在这里您可以设置语言、主题、动画、自动保存、备份设置和其他常规选项。",
    "help.settings.backup.title": "备份和恢复",
    "help.settings.backup.description": "创建数据备份或从以前的版本恢复它们。",
    "help.settings.backup.details": "应用程序创建自动备份。您也可以手动创建备份并从以前的状态恢复数据。",
    "help.keyboard.shortcuts.title": "键盘快捷键",
    "help.keyboard.shortcuts.description": "使用键盘快捷键以更快地工作。",
    "help.keyboard.shortcuts.details": "F1: 打开帮助菜单，Ctrl+Z / Cmd+Z: 撤销，Ctrl+Shift+Z / Cmd+Shift+Z: 重做，Ctrl+S / Cmd+S: 保存，Escape: 取消/关闭。",
    "help.tips.efficiency.title": "提高效率",
    "help.tips.efficiency.description": "高效工作的提示。",
    "help.tips.efficiency.details": "使用项目和任务来组织您的工作。为经常使用的耗材创建耗材预设。使用报价模板以更快地创建报价。",
  },
};

// Process each language file
const langFiles = {
  'es': 'language_es.ts',
  'fr': 'language_fr.ts',
  'it': 'language_it.ts',
  'pl': 'language_pl.ts',
  'pt': 'language_pt.ts',
  'ru': 'language_ru.ts',
  'sk': 'language_sk.ts',
  'uk': 'language_uk.ts',
  'zh': 'language_zh.ts',
};

Object.entries(langFiles).forEach(([langCode, filename]) => {
  if (!translations[langCode]) {
    console.log(`Skipping ${langCode} - no translations provided`);
    return;
  }
  
  console.log(`Processing ${langCode} (${filename})...`);
  
  let content = fs.readFileSync(filename, 'utf8');
  let modified = false;
  
  // Replace help translations
  Object.entries(translations[langCode]).forEach(([key, translatedValue]) => {
    // Escape quotes in the value
    const escapedValue = translatedValue.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
    // Find and replace the translation
    const pattern = new RegExp(`("${key.replace(/\./g, '\\.')}":\\s*)"[^"]*"`, 'g');
    const replacement = `$1"${escapedValue}"`;
    
    if (content.match(pattern)) {
      content = content.replace(pattern, replacement);
      modified = true;
    }
  });
  
  if (modified) {
    fs.writeFileSync(filename, content, 'utf8');
    console.log(`  ✓ Updated ${filename}`);
  } else {
    console.log(`  - No changes needed for ${filename}`);
  }
});

console.log('\nDone! All help translations have been updated.');

